language: python
python:
  - "2.7"
addons:
  apt:
    packages:
    - antiword
    - language-pack-he
install:
  - pip install --upgrade pip
  - pip install -r python/requirements.txt
  - pip install python/
script:
  - .travis/run_tests.sh
  - .travis/make_datapackage.sh
