language: python
python:
  - "2.7"
addons:
  artifacts:
    paths:
    - data/datapackage.zip
  apt:
    packages:
    - antiword
    - language-pack-he
install:
  - pip install --upgrade pip
  - pip install -r python/requirements.txt
  - pip install python/
script: 
  - .travis/script.sh
