language: python
python:
  - "2.7"
addons:
  apt:
    packages:
    - antiword
    - language-pack-he
install:
  - .travis/install.sh
script: 
  - .travis/script.sh
after_script:
  - pkill -fe -9 sshproxy || true
