language: python
python:
  - "2.7"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y antiword
install:
  - pip install --upgrade pip
  - pip install -r python/requirements.txt
  - pip install python/
script:
  - cd python && bin/run_tests.sh
  - .travis/make_datapackage.sh
