language: python
python:
  - "2.7"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y antiword
install:
  - pip install --upgrade pip
  - pip install -r python/requirements.txt
  - pip install python/
script:
  - cd python && bin/run_tests.sh
  - mkdir -p data && cd python && bin/make_datapackage.py --days 3 --debug --zip
