language: python
python:
  - "2.7"
addons:
  apt:
    packages:
    - antiword
    - language-pack-he
    - awscli
install:
  - pip install --upgrade pip
  - pip install -r python/requirements.txt
  - pip install python/
script: 
  - .travis/script.sh
